services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: watm-dt-backend
    restart: unless-stopped
    volumes:
      - ./data_parquet:/app/data_parquet:ro
      - ./data:/app/data:ro
      - ./config:/app/config:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - watm-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: watm-dt-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - watm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  watm-network:
    driver: bridge
