/**
 * Static data client for the frontend.
 *
 * Reads pre-built JSON files from /static-data (generated by
 * scripts/build_static_data.py) and reproduces the aggregation logic that the
 * FastAPI backend used to run server-side. Function signatures match the old
 * API client so pages and hooks are unaffected.
 */

// ============================================================================
// Type definitions (unchanged from the backend API client)
// ============================================================================

export interface TimePoint {
  step: number;
  time: number;
}

export interface SeriesData {
  variable: string;
  scenario: string;
  series: {
    time: number[];
    value: number[];
  };
}

export interface ScenarioResolution {
  scenario_name: string;
}

export interface ParameterValues {
  [key: string]: string | number | boolean;
}

export interface SeriesStatistics {
  variable: string;
  scenario: string;
  year_range: {
    start: number;
    end: number;
  };
  peak: {
    value: number;
    year: number;
  };
  valley: {
    value: number;
    year: number;
  };
  mean: number;
  std: number;
  trend: number;
  range: number;
  data_points: number;
}

export interface ClimateScenarioData {
  years: number[];
  values: number[];
}

export interface ClimateData {
  precipitation: Record<string, ClimateScenarioData>;
  temperature: Record<string, ClimateScenarioData>;
}

export interface YellowRiverBasinData {
  type: string;
  features: Array<{
    type: string;
    properties: Record<string, any>;
    geometry: {
      type: string;
      coordinates: any;
    };
  }>;
}

export interface MultiSeriesFilters {
  [parameterName: string]: number | number[];
}

export interface FilterSummary {
  requested: number | number[] | 'any';
  matched: number[] | string;
}

export interface MultiSeriesAggregateResponse {
  variable: string;
  n_scenarios: number;
  filter_summary: Record<string, FilterSummary>;
  series: {
    time: number[];
    mean: number[];
    std: number[];
    ci_lower: number[];
    ci_upper: number[];
    min: number[];
    max: number[];
    p05: number[];
    p95: number[];
  };
}

export interface ScenarioWithData {
  scenario_name: string;
  parameters: Record<string, number>;
  series: {
    time: number[];
    value: number[];
  };
}

export interface MultiSeriesRawResponse {
  variable: string;
  n_scenarios: number;
  scenarios: ScenarioWithData[];
}

// ============================================================================
// Static file loading with caching
// ============================================================================

interface StaticScenario {
  scenario_name: string;
  [parameter: string]: string | number;
}

interface TimeFile {
  years: number[];
  step0_year: number;
}

const cache = new Map<string, Promise<any>>();

function loadJson<T>(path: string): Promise<T> {
  let p = cache.get(path);
  if (!p) {
    p = fetch(path).then(res => {
      if (!res.ok) {
        throw new Error(`Failed to load static data: ${path} (${res.status})`);
      }
      return res.json();
    });
    cache.set(path, p);
  }
  return p as Promise<T>;
}

const seriesCache = new Map<string, Promise<Record<string, number[]>>>();

function loadSeries(safeName: string): Promise<Record<string, number[]>> {
  let p = seriesCache.get(safeName);
  if (!p) {
    p = loadJson<Record<string, number[]>>(`/static-data/series/${safeName}.json`);
    seriesCache.set(safeName, p);
  }
  return p;
}

async function loadNameToSafe(): Promise<Record<string, string>> {
  const file = await loadJson<{ name_to_safe: Record<string, string> }>(
    '/static-data/variables_map.json'
  );
  return file.name_to_safe;
}

async function loadScenarios(): Promise<StaticScenario[]> {
  return loadJson<StaticScenario[]>('/static-data/scenarios.json');
}

async function loadTime(): Promise<TimeFile> {
  return loadJson<TimeFile>('/static-data/time.json');
}

async function resolveSafeName(variable: string): Promise<string> {
  const nameToSafe = await loadNameToSafe();
  return nameToSafe[variable] ?? variable;
}

/** Slice a per-scenario series by (inclusive) year index range. */
function sliceSeries(
  values: number[],
  years: number[],
  startYear: number,
  endYear: number
): { time: number[]; value: number[] } {
  const start = Math.max(0, startYear);
  const end = Math.min(years.length - 1, endYear);
  const time: number[] = [];
  const value: number[] = [];
  for (let i = start; i <= end; i++) {
    time.push(years[i]);
    value.push(values[i]);
  }
  return { time, value };
}

// ============================================================================
// API functions (static implementations)
// ============================================================================

/**
 * Available variable safe names (excluding TIME).
 */
export async function getVariables(): Promise<string[]> {
  const nameToSafe = await loadNameToSafe();
  return Object.values(nameToSafe);
}

/**
 * Parameter name -> sorted unique values.
 */
export async function getParams(): Promise<Record<string, any[]>> {
  return loadJson<Record<string, any[]>>('/static-data/params.json');
}

/**
 * Resolve scenario name from parameter values (local exact match).
 * Mirrors the backend: unknown parameter -> error, no match -> error,
 * multiple matches -> first scenario.
 */
export async function resolveScenario(
  values: ParameterValues
): Promise<ScenarioResolution> {
  const scenarios = await loadScenarios();
  const paramKeys = Object.keys(values);
  for (const key of paramKeys) {
    if (!(key in scenarios[0])) {
      throw new Error(`Unknown parameter: ${key}`);
    }
  }
  const matched = scenarios.filter(sc =>
    paramKeys.every(key => sc[key] === values[key])
  );
  if (matched.length === 0) {
    throw new Error('No scenario matches the selected parameters');
  }
  return { scenario_name: matched[0].scenario_name };
}

/**
 * Time vector (step -> year). Steps are 1/16 year; yearly means are the
 * granularity of the static data, so steps map to year indices.
 */
export async function getTime(): Promise<TimePoint[]> {
  const t = await loadTime();
  return t.years.map((year, i) => ({ step: i * 16, time: year }));
}

/**
 * Fetch yearly time series for a specific variable and scenario.
 * start_step/end_step are raw 1/16-year steps; they map onto yearly means.
 */
export async function getSeries(
  variable: string,
  scenario: string,
  options?: {
    start_step?: number;
    end_step?: number;
  }
): Promise<SeriesData> {
  const safe = await resolveSafeName(variable);
  const [series, t] = await Promise.all([loadSeries(safe), loadTime()]);
  const values = series[scenario];
  if (!values) {
    throw new Error(`Scenario not found for variable: ${scenario}`);
  }
  const startYear =
    options?.start_step !== undefined ? Math.floor(options.start_step / 16) : 0;
  const endYear =
    options?.end_step !== undefined
      ? Math.floor(options.end_step / 16)
      : t.years.length - 1;
  const sliced = sliceSeries(values, t.years, startYear, endYear);
  return { variable, scenario, series: sliced };
}

/**
 * Statistics for a time series (peak/valley/mean/std/trend).
 */
export async function getSeriesStatistics(
  variable: string,
  scenario: string,
  options?: {
    start_year?: number;
    end_year?: number;
  }
): Promise<SeriesStatistics> {
  const safe = await resolveSafeName(variable);
  const [series, t] = await Promise.all([loadSeries(safe), loadTime()]);
  const values = series[scenario];
  if (!values) {
    throw new Error(`Scenario not found for variable: ${scenario}`);
  }
  const startYear = (options?.start_year ?? t.years[0]) - t.step0_year;
  const endYear = (options?.end_year ?? t.years[t.years.length - 1]) - t.step0_year;
  const sliced = sliceSeries(values, t.years, startYear, endYear);
  const { time, value } = sliced;
  const n = value.length;
  const mean = value.reduce((a, b) => a + b, 0) / n;
  const std = Math.sqrt(
    value.reduce((a, b) => a + (b - mean) ** 2, 0) / (n > 1 ? n - 1 : 1)
  );
  let peakYear = time[0];
  let valleyYear = time[0];
  let peak = value[0];
  let valley = value[0];
  value.forEach((v, i) => {
    if (v > peak) {
      peak = v;
      peakYear = time[i];
    }
    if (v < valley) {
      valley = v;
      valleyYear = time[i];
    }
  });
  const xMean = time.reduce((a, b) => a + b, 0) / n;
  let num = 0;
  let den = 0;
  time.forEach((x, i) => {
    num += (x - xMean) * (value[i] - mean);
    den += (x - xMean) ** 2;
  });
  const trend = den > 0 ? num / den : 0;
  return {
    variable,
    scenario,
    year_range: { start: time[0], end: time[n - 1] },
    peak: { value: peak, year: peakYear },
    valley: { value: valley, year: valleyYear },
    mean,
    std,
    trend,
    range: peak - valley,
    data_points: n,
  };
}

/**
 * Static deployments have no backend to ping.
 */
export async function healthCheck(): Promise<boolean> {
  return true;
}

/**
 * Climate scenario data for RCP pathways.
 */
export async function getClimateData(): Promise<ClimateData> {
  return loadJson<ClimateData>('/static-data/climate_data.json');
}

export async function getYellowRiverBasin(): Promise<YellowRiverBasinData> {
  const response = await fetch('/yellow_river_basin.geojson');
  if (!response.ok) {
    throw new Error(`Failed to fetch Yellow River Basin data: ${response.statusText}`);
  }
  return response.json();
}

async function fetchGeoJson(name: string): Promise<YellowRiverBasinData> {
  const response = await fetch(`/static-data/${name}.geojson`);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${name} data: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

export async function getSWNP(): Promise<YellowRiverBasinData> {
  return fetchGeoJson('swntp');
}

export async function getLoessPlateau(): Promise<YellowRiverBasinData> {
  return fetchGeoJson('loess_plateau');
}

export async function getMainRiver(): Promise<YellowRiverBasinData> {
  return fetchGeoJson('main_river');
}

export async function getStations(): Promise<YellowRiverBasinData> {
  return fetchGeoJson('stations');
}

// ============================================================================
// Multi-scenario query (client-side aggregation)
// ============================================================================

function matchesFilters(
  scenario: StaticScenario,
  filters: MultiSeriesFilters
): boolean {
  for (const [param, wanted] of Object.entries(filters)) {
    const actual = scenario[param];
    if (Array.isArray(wanted)) {
      if (!wanted.includes(actual as number)) return false;
    } else if (actual !== wanted) {
      return false;
    }
  }
  return true;
}

/** Linear-interpolation quantile, matching polars' default `linear` method. */
function quantile(sorted: number[], q: number): number {
  const n = sorted.length;
  if (n === 0) return NaN;
  if (n === 1) return sorted[0];
  const pos = (n - 1) * q;
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  if (lo === hi) return sorted[lo];
  const frac = pos - lo;
  return sorted[lo] * (1 - frac) + sorted[hi] * frac;
}

function sampleStd(values: number[], mean: number): number {
  if (values.length < 2) return 0;
  const sumSq = values.reduce((acc, v) => acc + (v - mean) ** 2, 0);
  return Math.sqrt(sumSq / (values.length - 1));
}

/**
 * Fetch time series for multiple scenarios matching flexible parameter filters.
 * Reproduces the backend /series/multi aggregation: mean/std/min/max/p05/p95
 * plus a 95% CI of the mean (se = std/sqrt(n) when n > 1).
 */
export async function getSeriesMulti(
  variable: string,
  filters: MultiSeriesFilters,
  options?: {
    start_year?: number;
    end_year?: number;
    aggregate?: boolean;
  }
): Promise<MultiSeriesAggregateResponse | MultiSeriesRawResponse> {
  const safe = await resolveSafeName(variable);
  const [series, scenarios, t] = await Promise.all([
    loadSeries(safe),
    loadScenarios(),
    loadTime(),
  ]);

  const matchedScenarios = scenarios.filter(sc => matchesFilters(sc, filters));
  if (matchedScenarios.length === 0) {
    throw new Error(`No scenarios found matching filters: ${JSON.stringify(filters)}`);
  }

  const startYear =
    options?.start_year !== undefined
      ? options.start_year - t.step0_year
      : 0;
  const endYear =
    options?.end_year !== undefined
      ? options.end_year - t.step0_year
      : t.years.length - 1;

  const aggregate = options?.aggregate !== false;

  if (!aggregate) {
    return {
      variable,
      n_scenarios: matchedScenarios.length,
      scenarios: matchedScenarios.map(sc => {
        const values = series[sc.scenario_name] ?? [];
        const sliced = sliceSeries(values, t.years, startYear, endYear);
        const parameters: Record<string, number> = {};
        for (const [k, v] of Object.entries(sc)) {
          if (k !== 'scenario_name') parameters[k] = v as number;
        }
        return { scenario_name: sc.scenario_name, parameters, series: sliced };
      }),
    };
  }

  const paramCols = Object.keys(matchedScenarios[0]).filter(k => k !== 'scenario_name');
  const nScenarios = matchedScenarios.length;
  const nYears = endYear - startYear + 1;

  const mean: number[] = [];
  const std: number[] = [];
  const min: number[] = [];
  const max: number[] = [];
  const p05: number[] = [];
  const p95: number[] = [];
  const ciLower: number[] = [];
  const ciUpper: number[] = [];
  const time: number[] = [];

  for (let i = startYear; i <= endYear; i++) {
    time.push(t.years[i]);
    const values: number[] = [];
    for (const sc of matchedScenarios) {
      const seriesForSc = series[sc.scenario_name];
      if (seriesForSc && seriesForSc[i] !== undefined) {
        values.push(seriesForSc[i]);
      }
    }
    const yMean = values.reduce((a, b) => a + b, 0) / values.length;
    const yStd = sampleStd(values, yMean);
    const sorted = [...values].sort((a, b) => a - b);
    const se = nScenarios > 1 ? yStd / Math.sqrt(nScenarios) : 0;
    mean.push(yMean);
    std.push(yStd);
    min.push(sorted[0]);
    max.push(sorted[sorted.length - 1]);
    p05.push(quantile(sorted, 0.05));
    p95.push(quantile(sorted, 0.95));
    ciLower.push(yMean - 1.96 * se);
    ciUpper.push(yMean + 1.96 * se);
  }

  const filterSummary: Record<string, FilterSummary> = {};
  for (const param of paramCols) {
    const unique = [...new Set(matchedScenarios.map(sc => sc[param]))].sort(
      (a, b) => Number(a) - Number(b)
    );
    filterSummary[param] = {
      requested: filters[param] ?? 'any',
      matched: unique.length <= 10 ? unique : `${unique.length} values`,
    };
  }

  return {
    variable,
    n_scenarios: nScenarios,
    filter_summary: filterSummary,
    series: { time, mean, std, ci_lower: ciLower, ci_upper: ciUpper, min, max, p05, p95 },
  };
}

/**
 * Convert ScenarioParameters to filter objects.
 * Omits null values (which represent "Any" in the frontend).
 */
export function parametersToFilters(parameters: {
  climateScenario: number | null;
  fertility: number | null;
  dietPattern: number | null;
  ecologicalFlow: number | null;
  irrigationEfficiency: number | null;
  fireGenerationShare: number | null;
}): MultiSeriesFilters {
  const filters: MultiSeriesFilters = {};

  if (parameters.climateScenario !== null) {
    filters['Climate change scenario switch for water yield'] = parameters.climateScenario;
  } else {
    // When climateScenario is null (Any), only consider RCP2.6 and RCP4.5 (values 1 and 2)
    // Both scenarios now use RCP4.5 for consistency
    filters['Climate change scenario switch for water yield'] = [1, 2];
  }
  if (parameters.fertility !== null) {
    filters['Fertility Variation'] = parameters.fertility;
  }
  if (parameters.dietPattern !== null) {
    filters['Diet change scenario switch'] = parameters.dietPattern;
  }
  if (parameters.ecologicalFlow !== null) {
    filters['Ecological water flow variable'] = parameters.ecologicalFlow;
  }
  if (parameters.irrigationEfficiency !== null) {
    filters['water saving irrigation efficiency ratio'] = parameters.irrigationEfficiency;
  }
  if (parameters.fireGenerationShare !== null) {
    filters['fire generation share province target'] = parameters.fireGenerationShare;
  }

  return filters;
}
